package lt.vu.psk.mybatis.model;

public class DutiesRepresentatives {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DUTIES_REPRESENTATIVES.REPRESENTATIVE_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    private Integer representativeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DUTIES_REPRESENTATIVES.DUTY_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    private Integer dutyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DUTIES_REPRESENTATIVES.REPRESENTATIVE_ID
     *
     * @return the value of PUBLIC.DUTIES_REPRESENTATIVES.REPRESENTATIVE_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public Integer getRepresentativeId() {
        return representativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DUTIES_REPRESENTATIVES.REPRESENTATIVE_ID
     *
     * @param representativeId the value for PUBLIC.DUTIES_REPRESENTATIVES.REPRESENTATIVE_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public void setRepresentativeId(Integer representativeId) {
        this.representativeId = representativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DUTIES_REPRESENTATIVES.DUTY_ID
     *
     * @return the value of PUBLIC.DUTIES_REPRESENTATIVES.DUTY_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public Integer getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DUTIES_REPRESENTATIVES.DUTY_ID
     *
     * @param dutyId the value for PUBLIC.DUTIES_REPRESENTATIVES.DUTY_ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public void setDutyId(Integer dutyId) {
        this.dutyId = dutyId;
    }
}