package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.Duty;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DUTY
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DUTY
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int insert(Duty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DUTY
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    Duty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DUTY
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    List<Duty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DUTY
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int updateByPrimaryKey(Duty record);

    int getResultCountByDutyName(String name);

    Duty findByName(String name);
}