package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.Representative;
import org.mybatis.cdi.Mapper;

@Mapper
public interface RepresentativeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REPRESENTATIVE
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REPRESENTATIVE
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int insert(Representative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REPRESENTATIVE
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    Representative selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REPRESENTATIVE
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    List<Representative> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REPRESENTATIVE
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    int updateByPrimaryKey(Representative record);
}