package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.Structure;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STRUCTURE
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STRUCTURE
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    int insert(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STRUCTURE
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    Structure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STRUCTURE
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    List<Structure> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STRUCTURE
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    int updateByPrimaryKey(Structure record);
}