package lt.vu.psk.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter @Setter
public class Representative {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REPRESENTATIVE.ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    private String representativeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_LAST_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    private String representativeLastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REPRESENTATIVE.ID
     *
     * @return the value of PUBLIC.REPRESENTATIVE.ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REPRESENTATIVE.ID
     *
     * @param id the value for PUBLIC.REPRESENTATIVE.ID
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_NAME
     *
     * @return the value of PUBLIC.REPRESENTATIVE.REPRESENTATIVE_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public String getRepresentativeName() {
        return representativeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_NAME
     *
     * @param representativeName the value for PUBLIC.REPRESENTATIVE.REPRESENTATIVE_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public void setRepresentativeName(String representativeName) {
        this.representativeName = representativeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_LAST_NAME
     *
     * @return the value of PUBLIC.REPRESENTATIVE.REPRESENTATIVE_LAST_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public String getRepresentativeLastName() {
        return representativeLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REPRESENTATIVE.REPRESENTATIVE_LAST_NAME
     *
     * @param representativeLastName the value for PUBLIC.REPRESENTATIVE.REPRESENTATIVE_LAST_NAME
     *
     * @mbg.generated Wed May 18 11:32:46 EEST 2022
     */
    public void setRepresentativeLastName(String representativeLastName) {
        this.representativeLastName = representativeLastName;
    }

    private List<Duty> dutyList;
}