package lt.vu.psk.mybatis.model;

public class Structure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STRUCTURE.ID
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STRUCTURE.STRUCTURE_NAME
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    private String structureName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STRUCTURE.ID
     *
     * @return the value of PUBLIC.STRUCTURE.ID
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STRUCTURE.ID
     *
     * @param id the value for PUBLIC.STRUCTURE.ID
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STRUCTURE.STRUCTURE_NAME
     *
     * @return the value of PUBLIC.STRUCTURE.STRUCTURE_NAME
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    public String getStructureName() {
        return structureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STRUCTURE.STRUCTURE_NAME
     *
     * @param structureName the value for PUBLIC.STRUCTURE.STRUCTURE_NAME
     *
     * @mbg.generated Wed May 18 11:32:45 EEST 2022
     */
    public void setStructureName(String structureName) {
        this.structureName = structureName;
    }
}